"""empty message

Revision ID: 8ddf95d498f9
Revises: 
Create Date: 2020-11-19 01:44:32.337009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ddf95d498f9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('UserRegister',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=30), nullable=False),
    sa.Column('confirm', sa.Boolean(), nullable=True),
    sa.Column('about_me', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=20), nullable=True),
    sa.Column('regist_date', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('password_hash'),
    sa.UniqueConstraint('username')
    )
    op.create_table('BlogMains',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('blog_name', sa.String(length=30), nullable=False),
    sa.Column('blog_descri', sa.String(length=200), nullable=True),
    sa.Column('blog_create_date', sa.DateTime(), nullable=True),
    sa.Column('author', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author'], ['UserRegister.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('BlogMains')
    op.drop_table('UserRegister')
    # ### end Alembic commands ###
